const dadesForaster = [
  {
    "Temporada": 1,
    "Color": "#EF4444",
    "Capitols": [
      {
        "id": "t1-benifallet",
        "Municipi": "Benifallet",
        "Coords": [40.9758333, 0.5177777],
        "Link": "https://www.google.com/search?q=El+Foraster+Benifallet",
        "Resum": "Descobreix una petita vila de l'Ebre amb gran esperit comunitari.",
        "Habitants": "706",
        "Extensio": "62,4 km²",
        "VideoId": "",
        "Alcalde": "Maria Mercè Pedret i Ramos",
        "Emissio": "25 de setembre del 2013",
        "Comarca": "Baix Ebre",
        "Gentilic": "benifalletenc",
        "Altitud": "19 m",
        "Bandera": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Escut_de_Benifallet.svg/500px-Escut_de_Benifallet.svg.png"
      },
      {
        "id": "t1-brafim",
        "Municipi": "Bràfim",
        "Coords": [41.499, 1.290],
        "Link": "https://www.google.com/search?q=El+Foraster+Bràfim",
        "Resum": "Un poble de la Conca amb tradicions vinícoles molt arrelades.",
        "Habitants": "1.506",
        "Extensio": "26,3 km²",
        "VideoId": "",
        "Alcalde": "Jeroni Palou i Cuadra",
        "Emissio": "2 d'octubre del 2013",
        "Comarca": "Conca de Barberà",
        "Gentilic": "brafimenc",
        "Altitud": "374 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Bràfim.svg"
      },
      {
        "id": "t1-peramola",
        "Municipi": "Peramola",
        "Coords": [42.019, 0.941],
        "Link": "https://www.google.com/search?q=El+Foraster+Peramola",
        "Resum": "Una visita a l'Alt Urgell plena de natura i llegendes.",
        "Habitants": "304",
        "Extensio": "63,3 km²",
        "VideoId": "",
        "Alcalde": "Olga Llobet i Sala",
        "Emissio": "9 d'octubre del 2013",
        "Comarca": "Alt Urgell",
        "Gentilic": "peramolenc",
        "Altitud": "670 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Peramola.svg"
      },
      {
        "id": "t1-tortella",
        "Municipi": "Tortellà",
        "Coords": [42.252, 2.389],
        "Link": "https://www.google.com/search?q=El+Foraster+Tortellà",
        "Resum": "Descobreix els paisatges volcànics d'Olot amb un toc d'humor.",
        "Habitants": "312",
        "Extensio": "34,2 km²",
        "VideoId": "",
        "Alcalde": "Roc Llopart i Cairol",
        "Emissio": "16 d'octubre del 2013",
        "Comarca": "Garrotxa",
        "Gentilic": "tortellan",
        "Altitud": "365 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Tortellà.svg"
      },
      {
        "id": "t1-belianes",
        "Municipi": "Belianes",
        "Coords": [41.447, 1.011],
        "Link": "https://www.google.com/search?q=El+Foraster+Belianes",
        "Resum": "En Quim viatja a un indret amb encant medieval i bona gent.",
        "Habitants": "593",
        "Extensio": "17,2 km²",
        "VideoId": "",
        "Alcalde": "Josep Bofill Garcia",
        "Emissio": "23 d'octubre del 2013",
        "Comarca": "Urgell",
        "Gentilic": "belianí",
        "Altitud": "369 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Belianes.svg"
      },
      {
        "id": "t1-els-muntells",
        "Municipi": "Els Muntells",
        "Coords": [40.709, 0.451],
        "Link": "https://www.google.com/search?q=El+Foraster+Els+Muntells",
        "Resum": "Un petit poble de l'Ebre que amaga molta història.",
        "Habitants": "204",
        "Extensio": "9,3 km²",
        "VideoId": "",
        "Alcalde": "Josep Vázquez",
        "Emissio": "30 d'octubre del 2013",
        "Comarca": "Montsià",
        "Gentilic": "muntellenc",
        "Altitud": "17 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_d%27Els_Muntells.svg"
      },
      {
        "id": "t1-la-vall-fosca",
        "Municipi": "La Vall Fosca",
        "Coords": [42.417, 0.775],
        "Link": "https://www.google.com/search?q=El+Foraster+La+Vall+Fosca",
        "Resum": "En Quim treu suc a la impressionant vall pirinenca.",
        "Habitants": "241",
        "Extensio": "208,0 km²",
        "VideoId": "",
        "Alcalde": "Salvador Taramona Merino",
        "Emissio": "20 de novembre del 2013",
        "Comarca": "Pallars Jussà",
        "Gentilic": "vallfosquí",
        "Altitud": "743 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_La_Vall_Fosca.svg"
      },
      {
        "id": "t1-port-de-la-selva",
        "Municipi": "Port de la Selva",
        "Coords": [42.371, 3.225],
        "Link": "https://www.google.com/search?q=El+Foraster+Port+de+la+Selva",
        "Resum": "Mar Mediterrània i tradicions marineres a l'Alt Empordà.",
        "Habitants": "1.075",
        "Extensio": "36,4 km²",
        "VideoId": "",
        "Alcalde": "Alejandro Avello",
        "Emissio": "27 de novembre del 2013",
        "Comarca": "Alt Empordà",
        "Gentilic": "selvatà",
        "Altitud": "2 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_del_Port_de_la_Selva.svg"
      },
      {
        "id": "t1-santa-maria-d-olo",
        "Municipi": "Santa Maria d'Oló",
        "Coords": [41.693, 1.863],
        "Link": "https://www.google.com/search?q=El+Foraster+Santa+Maria+d%27Oló",
        "Resum": "Rutes de muntanya i festes majors per conèixer l'essència del Berguedà.",
        "Habitants": "331",
        "Extensio": "50,7 km²",
        "VideoId": "",
        "Alcalde": "Josep Tito",
        "Emissio": "4 de desembre del 2013",
        "Comarca": "Moianès",
        "Gentilic": "olotí",
        "Altitud": "358 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Santa_Maria_d%27Oló.svg"
      },
      {
        "id": "t1-salardu",
        "Municipi": "Salardú",
        "Coords": [42.700, 0.969],
        "Link": "https://www.google.com/search?q=El+Foraster+Salardú",
        "Resum": "Un petit poble de muntanya ple de neu i tradició aranesa.",
        "Habitants": "277",
        "Extensio": "16,6 km²",
        "VideoId": "",
        "Alcalde": "Miguelito Ortiz",
        "Emissio": "15 de gener del 2014",
        "Comarca": "Vall d'Aran",
        "Gentilic": "salardunenc",
        "Altitud": "1.066 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Salardú.svg"
      },
      {
        "id": "t1-borreda",
        "Municipi": "Borredà",
        "Coords": [42.156, 1.954],
        "Link": "https://www.google.com/search?q=El+Foraster+Borredà",
        "Resum": "Descobrint els encants rurals del Berguedà i la calç viva.",
        "Habitants": "307",
        "Extensio": "18,4 km²",
        "VideoId": "",
        "Alcalde": "Isidre Balet",
        "Emissio": "22 de gener del 2014",
        "Comarca": "Berguedà",
        "Gentilic": "borredanès",
        "Altitud": "788 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Borredà.svg"
      },
      {
        "id": "t1-espolla",
        "Municipi": "Espolla",
        "Coords": [42.358, 3.139],
        "Link": "https://www.google.com/search?q=El+Foraster+Espolla",
        "Resum": "Un poble de l'Alt Empordà on natura i cultura conviuen tranquil·lament.",
        "Habitants": "160",
        "Extensio": "43,0 km²",
        "VideoId": "",
        "Alcalde": "Vicenç Majoral",
        "Emissio": "29 de gener del 2014",
        "Comarca": "Alt Empordà",
        "Gentilic": "espollenc",
        "Altitud": "125 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Espolla.svg"
      }
    ]
  },
  {
    "Temporada": 2,
    "Color": "#efd544",
    "Capitols": [
      {
        "id": "t2-godall",
        "Municipi": "Godall",
        "Coords": [41.158, 0.451],
        "Link": "https://www.google.com/search?q=El+Foraster+Godall",
        "Resum": "Un racó del Baix Ebre amb història i tradicions vívides.",
        "Habitants": "358",
        "Extensio": "25,9 km²",
        "VideoId": "",
        "Alcalde": "Guillem Olivella",
        "Emissio": "4 de maig del 2014",
        "Comarca": "Baix Ebre",
        "Gentilic": "godallenc",
        "Altitud": "249 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Godall.svg"
      },
      {
        "id": "t2-mollo",
        "Municipi": "Molló",
        "Coords": [42.435, 2.491],
        "Link": "https://www.google.com/search?q=El+Foraster+Molló",
        "Resum": "A la frontera amb França, cultura i natura es troben.",
        "Habitants": "387",
        "Extensio": "43,7 km²",
        "VideoId": "",
        "Alcalde": "Francesc Xavier Fàbrega",
        "Emissio": "11 de maig del 2014",
        "Comarca": "Ripollès",
        "Gentilic": "molloenc",
        "Altitud": "668 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Molló.svg"
      },
      {
        "id": "t2-llafranc",
        "Municipi": "Llafranc",
        "Coords": [41.802, 3.142],
        "Link": "https://www.google.com/search?q=El+Foraster+Llafranc",
        "Resum": "Platja i tradició marinera en una vila empordanesa acollidora.",
        "Habitants": "353",
        "Extensio": "1,8 km²",
        "VideoId": "",
        "Alcalde": "Joan Àlvarez Marco",
        "Emissio": "18 de maig del 2014",
        "Comarca": "Baix Empordà",
        "Gentilic": "llafranquí",
        "Altitud": "20 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Llafranc.svg"
      },
      {
        "id": "t2-prades",
        "Municipi": "Prades",
        "Coords": [41.354, 0.843],
        "Link": "https://www.google.com/search?q=El+Foraster+Prades",
        "Resum": "A la muntanya de Prades, cultura popular i paisatges d'alta muntanya.",
        "Habitants": "1.500",
        "Extensio": "37,0 km²",
        "VideoId": "",
        "Alcalde": "Lluís Garcia Lázaro",
        "Emissio": "1 de juny del 2014",
        "Comarca": "Baix Camp",
        "Gentilic": "pradenc",
        "Altitud": "950 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Prades.svg"
      },
      {
        "id": "t2-alfes",
        "Municipi": "Alfés",
        "Coords": [41.233, 0.694],
        "Link": "https://www.google.com/search?q=El+Foraster+Alfés",
        "Resum": "Descobrint les arrels arqueològiques i la tranquil·litat del Segrià.",
        "Habitants": "730",
        "Extensio": "28,6 km²",
        "VideoId": "",
        "Alcalde": "Ricard Pueyo",
        "Emissio": "8 de juny del 2014",
        "Comarca": "Segrià",
        "Gentilic": "alfesenc",
        "Altitud": "213 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_d%27Alfés.svg"
      },
      {
        "id": "t2-osor",
        "Municipi": "Osor",
        "Coords": [41.992, 2.446],
        "Link": "https://www.google.com/search?q=El+Foraster+Osor",
        "Resum": "Un petit poblet gironí amb cultura de molí i ponts de llegenda.",
        "Habitants": "270",
        "Extensio": "17,5 km²",
        "VideoId": "",
        "Alcalde": "Emili Pujol",
        "Emissio": "15 de juny del 2014",
        "Comarca": "Selva",
        "Gentilic": "osorenc",
        "Altitud": "368 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_d%27Osor.svg"
      },
      {
        "id": "t2-la-torre-de-lespanyol",
        "Municipi": "La Torre de l'Espanyol",
        "Coords": [41.205, 1.083],
        "Link": "https://www.google.com/search?q=El+Foraster+La+Torre+de+l%27Espanyol",
        "Resum": "Una llarga història a la Terra Alta des d'una perspectiva de poble tranquil.",
        "Habitants": "461",
        "Extensio": "26,8 km²",
        "VideoId": "",
        "Alcalde": "Eladi Galdeano",
        "Emissio": "22 de juny del 2014",
        "Comarca": "Terra Alta",
        "Gentilic": "torreà",
        "Altitud": "231 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_la_Torre_de_l%27Espanyol.svg"
      },
      {
        "id": "t2-arseguel",
        "Municipi": "Arsèguel",
        "Coords": [42.052, 1.222],
        "Link": "https://www.google.com/search?q=El+Foraster+Arsèguel",
        "Resum": "Un dels pobles més petits del món, però amb una gran comunitat viva.",
        "Habitants": "100",
        "Extensio": "19,0 km²",
        "VideoId": "",
        "Alcalde": "Jaume Mas",
        "Emissio": "29 de juny del 2014",
        "Comarca": "Alt Urgell",
        "Gentilic": "arseguelí",
        "Altitud": "915 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_d%27Arsèguel.svg"
      }
    ]
  },
  {
    "Temporada": 3,
    "Color": "#6cef44",
    "Capitols": [
      {
        "id": "t3-sant-llorenc-de-morunys",
        "Municipi": "Sant Llorenç de Morunys",
        "Coords": [42.110, 1.454],
        "Link": "https://www.google.com/search?q=El+Foraster+Sant+Llorenç+de+Morunys",
        "Resum": "Un lloc emblemàtic del solsonès, ple de llegendes i paisatges.",
        "Habitants": "1.050",
        "Extensio": "4,2 km²",
        "VideoId": "",
        "Alcalde": "Maria Mercè Pedret",
        "Emissio": "12 de gener del 2015",
        "Comarca": "Solsonès",
        "Gentilic": "morunyenc",
        "Altitud": "750 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Sant_Llorenç_de_Morunys.svg"
      }
    ]
  },
  {
    "Temporada": 4,
    "Color": "#44e9ef",
    "Capitols": [
      {
        "id": "t4-cases-d-alcanar",
        "Municipi": "Cases d'Alcanar",
        "Coords": [40.610, 0.529],
        "Link": "https://www.google.com/search?q=El+Foraster+Cases+d%27Alcanar",
        "Resum": "Comunitat costanera amb arrels de pagesia a l'Ebre.",
        "Habitants": "750",
        "Extensio": "9,5 km²",
        "VideoId": "",
        "Alcalde": "Rafael Simó",
        "Emissio": "13 de gener del 2016",
        "Comarca": "Montsià",
        "Gentilic": "alcanarenc",
        "Altitud": "5 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_Cases_d%27Alcanar.svg"
      }
    ]
  },
  {
    "Temporada": 5,
    "Color": "#4472ef",
    "Capitols": [
      {
        "id": "t5-barceloneta",
        "Municipi": "Barceloneta",
        "Coords": [41.377, 2.189],
        "Link": "https://www.google.com/search?q=El+Foraster+Barceloneta",
        "Resum": "El barri marítim de Barcelona, amb la seva ànima popular.",
        "Habitants": "16.640",
        "Extensio": "1,1 km²",
        "VideoId": "",
        "Alcalde": "Quim Masferrer",
        "Emissio": "26 d'abril del 2017",
        "Comarca": "Barcelonès",
        "Gentilic": "barceloní",
        "Altitud": "10 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_d%27El_Prat_de_Llobregat.svg"
      }
    ]
  },
  {
    "Temporada": 6,
    "Color": "#9c44ef",
    "Capitols": [
      {
        "id": "t6-santa-pau",
        "Municipi": "Santa Pau",
        "Coords": [42.189, 2.520],
        "Link": "https://www.google.com/search?q=El+Foraster+Santa+Pau",
        "Resum": "Poble amb encant medieval a la Garrotxa volcànica.",
        "Habitants": "533",
        "Extensio": "55,7 km²",
        "VideoId": "",
        "Alcalde": "Anna Ribas Romagosa",
        "Emissio": "7 de novembre del 2018",
        "Comarca": "Garrotxa",
        "Gentilic": "pauenc",
        "Altitud": "538 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Santa_Pau.svg"
      }
    ]
  },
  {
    "Temporada": 7,
    "Color": "#ef447d",
    "Capitols": [
      {
        "id": "t7-l-estany",
        "Municipi": "L'Estany",
        "Coords": [41.843, 2.602],
        "Link": "https://www.google.com/search?q=El+Foraster+L%27Estany",
        "Resum": "Amb la gran església romànica i un llac tranquil, el poble sorprèn.",
        "Habitants": "630",
        "Extensio": "5,4 km²",
        "VideoId": "",
        "Alcalde": "Isaac Peraire",
        "Emissio": "16 de novembre del 2020",
        "Comarca": "Maresme",
        "Gentilic": "estanyenc",
        "Altitud": "48 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_L%27Estany.svg"
      }
    ]
  },
  {
    "Temporada": 8,
    "Color": "#ef4486",
    "Capitols": [
      {
        "id": "t8-verges",
        "Municipi": "Verges",
        "Coords": [42.237, 2.887],
        "Link": "https://www.google.com/search?q=El+Foraster+Verges",
        "Resum": "Famosa per la seva dansa de la mort, un poble amb tradició pròpia.",
        "Habitants": "2.000",
        "Extensio": "23,1 km²",
        "VideoId": "",
        "Alcalde": "Isidre Gironès",
        "Emissio": "12 de setembre de 2022",
        "Comarca": "Baix Empordà",
        "Gentilic": "vergità",
        "Altitud": "62 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Verges.svg"
      }
    ]
  },
  {
    "Temporada": 9,
    "Color": "#6944ef",
    "Capitols": [
      {
        "id": "t9-sant-pol-de-mar",
        "Municipi": "Sant Pol de Mar",
        "Coords": [41.604, 2.629],
        "Link": "https://www.google.com/search?q=El+Foraster+Sant+Pol+de+Mar",
        "Resum": "Un barri mariner amb vistes al Mediterrani i una comunitat viva.",
        "Habitants": "5.500",
        "Extensio": "7,6 km²",
        "VideoId": "",
        "Alcalde": "David Bote Salvador",
        "Emissio": "25 de novembre del 2024",
        "Comarca": "Maresme",
        "Gentilic": "santpolenc",
        "Altitud": "10 m",
        "Bandera": "https://commons.wikimedia.org/wiki/File:Escut_de_Sant_Pol_de_Mar.svg"
      }
    ]
  }
];